name: Build

on:
  - push

jobs:
  dependencies:
    name: Build dependencies
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Create global variables
        id: version
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"

  build:
    name: Build documents
    needs: dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sources:
          - input: unplugged-en.tex
            output: unplugged-en.pdf
          - input: unplugged-zh-cn.tex
            output: unplugged-zh-cn.pdf

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Build documents using LaTeX (${{ matrix.sources.input }})
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          root_file: ${{ matrix.sources.input }}
          latexmk_shell_escape: true

      - name: Upload build assets (${{ matrix.sources.output }})
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.sources.output }}
          path: src/${{ matrix.sources.output }}

  release:
    name: "Create Github tag/pre-release"
    runs-on: ubuntu-latest
    needs: [dependencies,build]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Github pre-release (${{ needs.dependencies.outputs.version }})
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.dependencies.outputs.version }}
          release_name: Version ${{ needs.dependencies.outputs.version }}
          draft: false
          prerelease: true

  assets:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: [dependencies,release]
    strategy:
      matrix:
        assets:
          - source: unplugged-en.pdf
            destination: unplugged-en
          - source: unplugged-cz-cn.pdf
            destination: unplugged-cz-cn

    steps:
      - name: Download build assets (${{ matrix.assets.source }})
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.assets.source }}
          path: ${{ matrix.assets.source }}

      - name: Upload release assets (${{ matrix.assets.destination }}${{ needs.dependencies.outputs.version }}.pdf)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ matrix.assets.source }}/${{ matrix.assets.source }}
          asset_name: ${{ matrix.assets.destination }}${{ needs.dependencies.outputs.version }}.pdf
          asset_content_type: application/pdf
